"""Auto-detect installed AI tools and generate configuration."""

from __future__ import annotations

import shutil
from dataclasses import dataclass


@dataclass
class DetectedBackend:
    name: str
    backend: str
    available: bool
    binary_path: str | None
    install_hint: str
    default_model_id: str
    default_weight: float


@dataclass
class DetectedHook:
    tool: str
    available: bool
    binary_path: str | None
    note: str | None = None


KNOWN_BACKENDS = [
    DetectedBackend(
        name="claude",
        backend="claude",
        available=False,
        binary_path=None,
        install_hint="npm i -g @anthropic-ai/claude-code",
        default_model_id="claude-sonnet-4-6",
        default_weight=1.0,
    ),
    DetectedBackend(
        name="gemini",
        backend="gemini",
        available=False,
        binary_path=None,
        install_hint="npm i -g @google/gemini-cli  OR  brew install gemini-cli",
        default_model_id="gemini-2.5-pro",
        default_weight=1.0,
    ),
    DetectedBackend(
        name="codex",
        backend="codex",
        available=False,
        binary_path=None,
        install_hint="npm i -g @openai/codex",
        default_model_id="o3",
        default_weight=1.0,
    ),
    DetectedBackend(
        name="ollama",
        backend="ollama",
        available=False,
        binary_path=None,
        install_hint="https://ollama.com/download",
        default_model_id="llama3.1:8b",
        default_weight=0.8,
    ),
]

KNOWN_HOOK_TOOLS = [
    "claude",
    "gemini",
    "codex",
    "cursor",
    "windsurf",
    "aider",
    "opencode",
    "cline",
]


def detect_backends() -> list[DetectedBackend]:
    """Detect which AI backends are available on this system."""
    detected: list[DetectedBackend] = []
    for template in KNOWN_BACKENDS:
        path = shutil.which(template.backend)
        if path:
            detected.append(
                DetectedBackend(
                    name=template.name,
                    backend=template.backend,
                    available=True,
                    binary_path=path,
                    install_hint=template.install_hint,
                    default_model_id=template.default_model_id,
                    default_weight=template.default_weight,
                )
            )
    return detected


# Tools that are file-based (no CLI binary to detect)
_FILE_BASED_HOOKS = {"cline", "opencode"}


def detect_hooks() -> list[DetectedHook]:
    """Detect which AI coding tools are available for hook installation."""
    detected: list[DetectedHook] = []
    for tool in KNOWN_HOOK_TOOLS:
        if tool in _FILE_BASED_HOOKS:
            detected.append(
                DetectedHook(
                    tool=tool,
                    available=True,
                    binary_path=None,
                    note="file-based tool (no CLI binary needed)",
                )
            )
        else:
            path = shutil.which(tool)
            if path:
                detected.append(DetectedHook(tool=tool, available=True, binary_path=path))
    return detected


def generate_config_yaml(backends: list[DetectedBackend]) -> str:
    """Generate .aigate.yml content from detected backends."""
    lines = [
        "# Auto-generated by aigate init",
        "# Detected backends on this system",
        "",
        "models:",
    ]

    for b in backends:
        lines.extend(
            [
                f"  - name: {b.name}",
                f"    backend: {b.backend}",
                f"    model_id: {b.default_model_id}",
                f"    weight: {b.default_weight}",
                "    enabled: true",
                "    timeout_seconds: 120",
                "",
            ]
        )

    if not backends:
        lines.extend(
            [
                "  # No AI backends detected!",
                "  # Install at least one:",
                "",
            ]
        )
        for template in KNOWN_BACKENDS:
            lines.append(f"  #   {template.name}: {template.install_hint}")
        lines.append("")

    # Consensus strategy comment
    count = len(backends)
    if count == 0:
        lines.append("# Strategy: prefilter-only (no AI backends found)")
    elif count == 1:
        lines.append("# Strategy: single-model (1 backend detected)")
    elif count == 2:
        lines.append("# Strategy: dual-model consensus (2 backends detected)")
    else:
        lines.append(f"# Strategy: full multi-model consensus ({count} backends detected)")

    lines.extend(
        [
            "",
            "thresholds:",
            "  malicious: 0.6",
            "  suspicious: 0.5",
            "  disagreement: 0.4",
            "",
            "ecosystems:",
            "  - pypi",
            "  - npm",
            "  - pub",
            "",
            "cache_dir: ~/.aigate/cache",
            "cache_ttl_hours: 168  # 7 days",
            "max_analysis_level: l2_deep",
            "output_format: rich  # rich | json | sarif",
            "",
            "enrichment:",
            "  enabled: false",
            "  timeout_seconds: 10",
            "  osv:",
            "    enabled: true",
            "  deps_dev:",
            "    enabled: false",
            "  scorecard:",
            "    enabled: false",
            "  provenance:",
            "    enabled: false",
            "  context7:",
            "    enabled: false",
            "  web_search:",
            "    enabled: false",
        ]
    )

    return "\n".join(lines) + "\n"
